name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout quân bị
        uses: actions/checkout@v4

      - name: Thiết lập Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cài đặt phụ tùng
        run: npm install

      - name: Nấu code (Build)
        run: npm run build

      - name: Thiết lập Pages
        uses: actions/configure-pages@v4

      - name: Tải bản Build lên hệ thống
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Triển khai lên GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
  
 
